client
dev tun
proto udp
remote 127.0.0.1 1197
resolv-retry infinite
nobind
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
auth SHA512
auth-nocache
tls-version-min 1.2
verb 3
